### ISSUE TITLE
내배캠 안드로이드 앱개발 입문 개인과제 피드백

### ISSUE THREAD

**Issue by tutorhwang** [Jisung15/Profile#1]
### 총평
안녕하세요! 성진님 과제 열심히 한 티가 나네요!
앞으로는 코드 참조를 위해 github issue로 피드백을 드릴게요!
이번 과제 제출시 project 파일이 모두 올라와있지 않아 실제 사용해보진 못해 코드 리뷰로만 전달드려요.
다음 과제 제출시에는 project 관련 파일 전부 github에 올려주세요!

### 코드 피드백
> registerForActivityResult는 잘 구현하였네요! 자주 사용하다보면 점점 더 익숙해질거예요!

> data class를 통으로 Intent로 전달하는 부분은 구현이 안되었네요. 이부분 궁금하면 튜터룸으로 오세요!

> 여러 위젯을 활용해 보고 싶을 경우 android developer 사이트에서 다양한 위젯 활용 방법들이 소개되어 있어요. 부트 캠프 과정 중에 모든 것을 다 사용해볼 수 없기에, 스스로 찾아내서 구현해보는 방법을 배워가는 것이 가장 중요해요. 이 과정을 배울 수 있도록 도와드리도록 노력하고 있답니다!  
스위치의 경우 하단의 링크를 참고해 보세요!
https://developer.android.com/develop/ui/views/components/togglebutton?hl=ko

> ConstraintLayout에서는 match_parent 보다는 match_constraints(0dp)를 활용하도록 권고하고 있어요.
그래야 ConstraintLayout의 제약사항들이 더 잘 적용되어요.
참고해 보세요.
[https://developer.android.com/reference/androidx/constraintlayout/widget/ConstraintLayout#dimensions-constraints](https://github.com/ImGaram/nb_camp_project/issues/url)
https://github.com/Jisung15/Profile/blob/a9bbbbf4478c83d49d22a78acc10a88df8c8d184/app/src/main/res/layout/activity_home.xml#L34-L35

> marginStart/End 는 marginHorizontal로 대체가능해요.
https://github.com/Jisung15/Profile/blob/a9bbbbf4478c83d49d22a78acc10a88df8c8d184/app/src/main/res/layout/activity_home.xml#L36-L38

> 문자열 string은 string.xml을 크기 값들은 dimen.xml를 활용해 보세요. 현업에서는 절대 하드코딩을 하지 않아요.https://github.com/Jisung15/Profile/blob/a9bbbbf4478c83d49d22a78acc10a88df8c8d184/app/src/main/res/layout/activity_home.xml#L41

> 다양한 속성들을 활용해서 layout을 잘 구성하였어요.

> 그냥 바로 닫으시면 되어요.
`app:layout_constraintTop_toBottomOf="@+id/et_login_password"/>`
https://github.com/Jisung15/Profile/blob/a9bbbbf4478c83d49d22a78acc10a88df8c8d184/app/src/main/res/layout/activity_sign_in.xml#L104
> 변수 이름만 봐도 어떤 기능인지 파악할 수 있도록 이름을 지어주시는게 가독성 향상에 도움이 됩니다.
passwordTextView
nameTextView
https://github.com/Jisung15/Profile/blob/a9bbbbf4478c83d49d22a78acc10a88df8c8d184/app/src/main/java/com/example/profileapp/HomeActivity.kt#L32-L33
> Key 값은 상수로 관리해 주세요.
const val EXTRA_LOGIN_ID = "loginId"
엘비스 연산자를 잘 활용했네요.
https://github.com/Jisung15/Profile/blob/a9bbbbf4478c83d49d22a78acc10a88df8c8d184/app/src/main/java/com/example/profileapp/HomeActivity.kt#L38-L43

> 리스트를 두개로 나눈 이유가 있나요?
https://github.com/Jisung15/Profile/blob/a9bbbbf4478c83d49d22a78acc10a88df8c8d184/app/src/main/java/com/example/profileapp/HomeActivity.kt#L53-L62

> 보내야하는 정보의 갯수가 많을 경우 가끔 실수로 누락시키는 경우가 있어요. 그래서 User data css 등에 정보를 담아서 보내는 것이 좀 더 안정적이예요.
Intent의 변수명은 보통 intent로 많이 사용해요.
https://github.com/Jisung15/Profile/blob/a9bbbbf4478c83d49d22a78acc10a88df8c8d184/app/src/main/java/com/example/profileapp/SignInActivity.kt#L52-L59

> 예외처리에 걸릴 경우 이 변수는 만든 보람이 없어지죠. 코드의 효율성도 함께 고민이 되면 좋아요!
https://github.com/Jisung15/Profile/blob/a9bbbbf4478c83d49d22a78acc10a88df8c8d184/app/src/main/java/com/example/profileapp/SignUpActivity.kt#L41-L49

> try catch 시도했네요! 이번 과제에서 다양한 시도를 많이 한 것 같아요 멋집니다!
https://github.com/Jisung15/Profile/blob/a9bbbbf4478c83d49d22a78acc10a88df8c8d184/app/src/main/java/com/example/profileapp/SignUpActivity.kt#L52-L60

> 반복되는 코드네요! 재사용할 순 없을까요?
https://github.com/Jisung15/Profile/blob/a9bbbbf4478c83d49d22a78acc10a88df8c8d184/app/src/main/java/com/example/profileapp/SignUpActivity.kt#L73-L81

> 결국 UserClass를 보내면 한번만 putExtra하면 되겠죠? 도전해 봅시다!
https://github.com/Jisung15/Profile/blob/a9bbbbf4478c83d49d22a78acc10a88df8c8d184/app/src/main/java/com/example/profileapp/SignUpActivity.kt#L90-L93

> Parcelize 어노테이션을 잘 활용해서 깔끔하게 구현했네요.
User 정보를 담은 class니 이름을 그냥 User로 해도 괜찮을 것 같아요!
https://github.com/Jisung15/Profile/blob/a9bbbbf4478c83d49d22a78acc10a88df8c8d184/app/src/main/java/com/example/profileapp/UserClass.kt#L6-L7

**Comment by Jisung15** [comment]
정말 감사합니다!
